/**
 * MINDFEINT — About page  (redesigned, "0G Neural Dark" design language)
 */
import { useRef } from "react";
import { motion } from "motion/react";
import { Cpu, Database, Globe, ArrowLeft, Zap } from "lucide-react";

/* ─── types ─────────────────────────────────────── */
interface Props {
  onBack: () => void;
}

/* ─── 3-D tilt hook (same pattern as HowToPlay) ─── */
function useTilt(strength = 12) {
  const ref = useRef<HTMLDivElement>(null);

  function onMove(e: React.MouseEvent<HTMLDivElement>) {
    const el = ref.current;
    if (!el) return;
    const { left, top, width, height } = el.getBoundingClientRect();
    const x = (e.clientX - left) / width - 0.5;   // -0.5 → 0.5
    const y = (e.clientY - top) / height - 0.5;
    el.style.transform = `perspective(900px) rotateX(${-y * strength}deg) rotateY(${x * strength}deg) scale3d(1.03,1.03,1.03)`;
  }

  function onLeave() {
    if (ref.current) {
      ref.current.style.transform =
        "perspective(900px) rotateX(0deg) rotateY(0deg) scale3d(1,1,1)";
    }
  }

  return { ref, onMove, onLeave };
}

/* ─── tech pillar data ───────────────────────────── */
const PILLARS = [
  {
    label: "0G Compute",
    icon: Cpu,
    color: "brand-blue",
    body: "Verifiable inference — every AI answer is signed in a TEE so it's provably generated by a real model, not a cheap script.",
  },
  {
    label: "0G Storage",
    icon: Database,
    color: "brand-green",
    body: "Every round's full record is stored immutably on decentralised storage and is publicly retrievable by anyone, forever.",
  },
  {
    label: "0G Chain",
    icon: Globe,
    color: "brand-amber",
    body: "Each record is anchored on-chain, timestamped and tamper-proof — so results can never be quietly rigged after the fact.",
  },
] as const;

/* ─── colour map → Tailwind classes ─────────────── */
const colorMap: Record<string, { icon: string; bg: string; border: string }> = {
  "brand-blue":  { icon: "text-brand-blue",  bg: "bg-brand-blue/10",  border: "border-brand-blue/20"  },
  "brand-green": { icon: "text-brand-green", bg: "bg-brand-green/10", border: "border-brand-green/20" },
  "brand-amber": { icon: "text-brand-amber", bg: "bg-brand-amber/10", border: "border-brand-amber/20" },
};

/* ─── PillarCard component ───────────────────────── */
function PillarCard({
  label,
  icon: Icon,
  color,
  body,
  delay,
}: (typeof PILLARS)[number] & { delay: number }) {
  const { ref, onMove, onLeave } = useTilt(10);
  const c = colorMap[color];

  return (
    <motion.div
      ref={ref}
      onMouseMove={onMove}
      onMouseLeave={onLeave}
      initial={{ opacity: 0, y: 28 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay, ease: [0.22, 1, 0.36, 1] }}
      className="glass-card p-6 rounded-2xl perspective-card relative overflow-hidden cursor-default"
      style={{ transition: "transform 0.15s ease-out, box-shadow 0.15s ease-out" }}
    >
      {/* Neural-grid overlay (top-right corner) */}
      <div
        aria-hidden
        className="pointer-events-none absolute -top-6 -right-6 w-36 h-36 neural-grid opacity-30 rounded-full"
      />

      {/* Icon badge */}
      <div
        className={`relative z-10 w-10 h-10 rounded-xl flex items-center justify-center mb-4 border ${c.bg} ${c.border} ${c.icon}`}
      >
        <Icon className="w-5 h-5" />
      </div>

      {/* Title */}
      <h3 className="relative z-10 text-base font-bold font-display text-white mb-2 tracking-tight">
        {label}
      </h3>

      {/* Body */}
      <p className="relative z-10 text-text-muted text-sm leading-relaxed">
        {body}
      </p>
    </motion.div>
  );
}

/* ─── Main component ─────────────────────────────── */
export default function About({ onBack }: Props) {
  return (
    <div className="max-w-4xl mx-auto w-full space-y-10">

      {/* ── Header ─────────────────────────────────── */}
      <motion.div
        className="flex items-center gap-4"
        initial={{ opacity: 0, x: -16 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ duration: 0.4, ease: "easeOut" }}
      >
        <button
          onClick={onBack}
          aria-label="Go back"
          className="
            flex items-center justify-center
            bg-white/5 hover:bg-white/10
            border border-white/10 hover:border-brand-violet/40
            text-text-secondary hover:text-white
            p-2.5 rounded-xl cursor-pointer
            transition-all duration-200
          "
        >
          <ArrowLeft className="w-4 h-4" />
        </button>

        <h1 className="text-3xl md:text-4xl font-extrabold font-display text-white tracking-tight">
          About Mindfeint
        </h1>
      </motion.div>

      {/* ── Hero paragraph ─────────────────────────── */}
      <motion.p
        className="text-text-secondary text-lg leading-relaxed"
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.45, delay: 0.1, ease: "easeOut" }}
      >
        <span className="text-gradient-violet font-bold">Mindfeint</span> is a
        social-deduction game where one of six answers is a real person and the
        rest are AIs pretending to be them. The twist: the AIs are{" "}
        <b className="text-white font-bold">provably real</b>.
      </motion.p>

      {/* ── Second paragraph ───────────────────────── */}
      <motion.p
        className="text-text-muted leading-relaxed"
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.45, delay: 0.18, ease: "easeOut" }}
      >
        Every social &ldquo;spot the bot&rdquo; game asks you to trust the house
        &mdash; was that really an AI, or a human plant? A genuine model, or a
        cheap script? Mindfeint removes the trust. It&apos;s built on{" "}
        <b className="text-white">0G</b>, the only stack that lets a game prove
        its AI players are genuine and untampered.
      </motion.p>

      {/* ── Tech pillar cards ──────────────────────── */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-5">
        {PILLARS.map((p, i) => (
          <PillarCard key={p.label} {...p} delay={0.25 + i * 0.08} />
        ))}
      </div>

      {/* ── Footer badge ───────────────────────────── */}
      <motion.div
        className="
          bg-dark-card border border-white/8
          rounded-xl p-4
          flex items-center justify-between gap-3
          flex-wrap
        "
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.45, delay: 0.5, ease: "easeOut" }}
      >
        {/* Left — dot + label */}
        <div className="flex items-center gap-3 min-w-0">
          <span className="relative flex h-2.5 w-2.5 shrink-0">
            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-brand-violet opacity-60" />
            <span className="relative inline-flex rounded-full h-2.5 w-2.5 bg-brand-violet" />
          </span>
          <span className="text-text-secondary text-sm font-mono truncate">
            Built for The Zero Cup on 0G &middot; Galileo Testnet
          </span>
        </div>

        {/* Right — live badge */}
        <div className="flex items-center gap-1.5 shrink-0">
          <Zap className="w-3.5 h-3.5 text-brand-green" />
          <span className="text-brand-green text-xs font-mono font-semibold tracking-widest uppercase">
            Live on Testnet
          </span>
        </div>
      </motion.div>

    </div>
  );
}
